export const ERROR_CODES = [
  'VALIDATION_FAILED',
  'INVALID_CREDENTIALS',
  'UNAUTHENTICATED',
  'SESSION_INVALID',
  'SESSION_TIMED_OUT',
  'SESSION_EXPIRED',
  'SECURITY_ANSWER_INCORRECT',
  'USER_LOCKED',
  'USER_INACTIVE',
  'USER_BLOCKED',
  'PASSWORD_CHANGE_REQUIRED',
  'PASSWORD_EXPIRED',
  'RESET_ATTEMPTS_EXCEEDED',
  'FORBIDDEN',
  'CSRF_REJECTED',
  'NOT_FOUND',
  'USERNAME_TAKEN',
  'PASSWORD_POLICY_NOT_CONFIGURED',
  'CANNOT_DEACTIVATE_SELF',
  'CANNOT_CHANGE_OWN_ROLE',
  'PERMISSION_DENIED',
  'SUPPLIER_CODE_NOT_SELECTED',
  'SUPPLIER_CODE_NOT_ASSIGNED',
  'CANNOT_CHANGE_OWN_ACCESS',
  'ADMIN_USER_PROTECTED',
  'RIGHT_NOT_GRANTABLE',
  'ROLE_NOT_EDITABLE',
  'ROLE_NAME_TAKEN',
  'ROLE_IN_USE',
  'SUPPLIER_CODE_TAKEN',
  'LIQUOR_CATEGORY_CODE_TAKEN',
  'SESSION_LIMIT_REACHED',
  'SECURITY_QUESTION_NOT_SET',
  'SECURITY_QUESTION_DISABLED',
  'RESET_REQUEST_EXPIRED',
  'RESET_REQUEST_INVALID',
  'ENDPOINT_NOT_FOUND',
  'METHOD_NOT_ALLOWED',
  'UNSUPPORTED_MEDIA_TYPE',
  'REQUEST_INVALID',
  'REQUEST_REFUSED',
  'DATABASE_ERROR',
  'UNEXPECTED_ERROR',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

export const SESSION_ENDED_CODES: readonly ErrorCode[] = ['UNAUTHENTICATED', 'SESSION_INVALID', 'SESSION_TIMED_OUT'];

export const SESSION_EXPIRED_CODE: ErrorCode = 'SESSION_EXPIRED';

export function isKnownErrorCode(value: unknown): value is ErrorCode {
  return typeof value === 'string' && (ERROR_CODES as readonly string[]).includes(value);
}
