export const tokens = {
  color: {
    primary: '#2E3035',
    primaryDark: '#1C1D21',
    secondary: '#818286',
    secondaryDark: '#6C6D72',
    accent: '#ED1B24',
    accentDark: '#930708',
    accentTint: '#FDEAEB',
    success: '#147D43',
    successTint: '#E7F4EC',
    warning: '#ed6c02',
    error: '#c62828',
    info: '#0277bd',
    background: '#F4F4F6',
    surface: '#FFFFFF',
    border: '#DCDDE0',
    head: '#F1F1F3',
    textPrimary: '#1C1C1E',
    textSecondary: '#6C6D72',
    iconTint: '#FDEAEB',
    iconTintMuted: '#F1F1F3',
    gridHeaderText: '#FFFFFF',
    gridHeaderIcon: '#C5C6CA',
    gridStripe: '#F3F4F6',
    gridSeparator: '#6E7178',
  },
  shell: {
    sidebarWidth: 240,
    topBarHeight: 60,
    sidebarBg: '#222327',
    sidebarActiveBg: '#33353B',
    sidebarHoverBg: '#2B2D32',
    sidebarDivider: '#3C3F46',
    sidebarText: '#C5C6CA',
    sidebarTextMuted: '#818286',
    sidebarIcon: '#6E7178',
    sidebarActiveText: '#FFFFFF',
    liveBg: '#E7F4EC',
    avatarBg: '#EDEEF0',
    avatarText: '#3C3F46',
  },
  radius: 6,
  font: {
    overline: 11,
    caption: 13,
    body2: 14,
    body1: 15,
    subtitle: 16,
    sectionTitle: 18,
    cardTitle: 22,
    pageTitle: 26,
    figure: 30,
  },
  icon: {
    sm: 18,
    md: 21,
    lg: 24,
    xl: 32,
  },
  fontFamily: [
    '"Inter"',
    '"Segoe UI"',
    'system-ui',
    '-apple-system',
    '"Helvetica Neue"',
    'Roboto',
    'Arial',
    'sans-serif',
  ].join(','),
} as const;
